Add the project files to the branch and ready for review
youmari/project-review pull request #1
Opened 2021-10-22 21:13 UTC by youmari

2021-10-22 21:44 UTC, youmari commented
Hi there @youmari  👋 

You are doing great so far but it will be better if you made some better practices.

### Required Changes ♻️

- [ ]  Styles of your page are missing, try to make it look good by applying some CSS styles 

- [ ]  Fix your linters errors and apply best HTML practices (look at comments bellow ⬇️ )

- [ ]  It would be better if you use main element in the HTML file so we can know where the main part of your page is.

- [ ] I suggest you try not to leave blank lines without purpose in order for your code to look clean 💯 

###  To highlight 🎯

- Your PR title and description are professional ✔️

###  Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2021-10-22 21:47 UTC, youmari commented on index.html
> +    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
Try to make your scripts tag in the head element so it can all of them in one place organized and make the page loads faster

2021-10-22 21:54 UTC, youmari commented on index.html
> +
It would be better if you use the main element in order to know the main part of your page

2021-10-22 21:54 UTC, youmari commented on index.html
> +      </select>
In my opinion, it will be nice if you give your select element a titel so the user will have a better  idea and know what he/she should select

2021-10-22 21:54 UTC, youmari commented on index.html
> +      <button id="submit">Submit</button>
Try to give your button a type attribute so we'll know what is about

2021-10-25 08:33 UTC, Davidosky007 requested changes
## Hi @youmari 👋, 

Good job so far! 💪 
* NIce use of GitHub inline comments ✔️ 
* Good use of polite suggestions ✔️ 
* Clear and easy to understand comments ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- You can include emojis and gifs to make your code review more human-friendly 👽.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-25 08:33 UTC, Davidosky007 commented on index.html
> +    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
* Kindly explain why you request a change - it might be obvious for you but not for someone else. an example would be:  ` your first heading should be wrapped in an h1 tag, this is good for SEO and it tells search engine bots and web users what a page is about.` 👍

2021-10-25 08:33 UTC, Davidosky007 commented on index.html
> +      </select>
* Remember to explain why you request a change - it might be obvious for you but not for someone else.

2021-10-25 08:47 UTC, youmari commented
All the required changes are done!

2021-10-25 09:02 UTC, wandji20 approved these changes
## Hi @youmari  :raised_hands:

##### You have done exceptionally well, and have met all requirements for this project :+1:

# Status: Approved 👍 :partying_face: 

Your project has been approved, however, Keep up the good work.

## Congratulations :+1:  :fireworks: 

_Go ahead and merge this branch. Also, don't forget to submit the project completion form.
Good luck with your next project :mechanical_arm:  :slightly_smiling_face:_ 

 If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 20:52 UTC, closed without merging